Proposal practices addreadme
HighlandSolutions/development-standards pull request #25
Opened 2022-07-08 14:14 UTC by ashabrah

## Author checklist
- [ ] I'm proposing a single change in this PR.
- I believe the proposed standard:
  - [ ] benefits more than it costs us and
  - [ ] doesn't conflict with our people-first value.
- [ ] The standard's file(s) follow(s) [the established directory structure][directory-structure].
- I provided:
  - [ ] a succinct summary,
  - [ ] reasoning for the proposed change,
  - [ ] an example/instructions on how to embody the standard unless repealing, and
  - [ ] a longer explanation if appropriate.

*Check boxes if requirement met or irrelevant.*

## First reviewer checklist
***NOTE:** Some of the author's checklist items are intentionally omitted, because they are a matter of opinion and up for discussion with the whole team.*

- [ ] This PR contains a single change.
- [ ] The proposed standard follows [the established directory structure][directory-structure].
- The author provided:
  - [ ] a succinct summary,
  - [ ] reasoning for the proposed change, and
  - [ ] an example/instructions on how to embody the standard unless repealing.

*Check boxes if requirement met or irrelevant.*

[directory-structure]: ../tree/main/standards#directory-structure

2022-07-08 16:18 UTC, lisacatalano approved these changes

2022-07-22 16:22 UTC, hs-epearson submitted a review, later dismissed

2022-07-22 16:35 UTC, curtisblackwell requested changes
I like the impact and simplicity of the example/instructions section.

2022-07-22 16:35 UTC, curtisblackwell commented on standards/practices/addingReadMe.md
> +# Title
What's the title?

2022-07-22 16:35 UTC, curtisblackwell commented on standards/practices/addingReadMe.md
> +### Proposal to add a README
Is this adding something to the standard or a stray note/comment or…?

2022-07-22 16:35 UTC, curtisblackwell commented on standards/practices/addingReadMe.md
> +We add a README file to our codebase when we start a project
Missing punctuation.

2022-09-01 20:54 UTC, CristiDiaz505 approved these changes

2022-10-14 15:01 UTC, curtisblackwell requested changes

2022-10-14 15:01 UTC, curtisblackwell commented on standards/practices/addingReadMe.md
> +# Proposal to add a README
Can we call this "Adding READMEs" instead? It'll be more consistent with existing standards and the PR is a proposal, but once it's accepted and merged, this document will be a standard.

Can you also rename the file to `adding-readmes` for consistency?

I know these are somewhat tedious requests, but the more the standards grow, the more important consistency will become.

2022-10-14 16:16 UTC, curtisblackwell approved these changes

2022-10-14 16:18 UTC, sucitivel approved these changes

2022-10-14 16:19 UTC, merged